# Generated by Django 5.1 on 2025-03-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='special_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
