# Generated by Django 5.1 on 2024-09-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('product', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('delivery_fee', models.IntegerField(null=True)),
                ('total_cost', models.IntegerField()),
                ('notes', models.CharField(max_length=400, null=True)),
                ('mop', models.CharField(max_length=4)),
                ('payment_status', models.CharField(max_length=10)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('order_num', models.IntegerField()),
            ],
        ),
    ]
