# Generated by Django 5.1 on 2024-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_date_alter_orders_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_id',
            field=models.CharField(max_length=100),
        ),
    ]
