# Generated by Django 5.1 on 2024-10-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0003_alter_orders_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
    ]
