# Generated by Django 5.1 on 2024-10-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_client_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
