# Generated by Django 5.1 on 2024-10-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_method_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('EFT', 'EFT'), ('Card', 'Card')], default='Cash', max_length=10),
        ),
    ]
