# Generated by Django 5.1 on 2024-10-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_orderitem_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(choices=[('Rooikrans', 'Rooikrans'), ('Black Wattle', 'Black Wattle'), ('Bloekom', 'Bloekom'), ('Myrtle', 'Myrtle'), ('Bags RK lg', 'Bags RK lg'), ('Bags RK sm', 'Bags RK sm'), ('Bags BW lg', 'Bags BW lg'), ('Bags BK lg', 'Bags BK lg'), ('Bags Namibian 18kg', 'Bags Namibian 18kg'), ('Bags Namibian 10kg', 'Bags Namibian 10kg')], max_length=100),
        ),
    ]
