# Generated by Django 5.1 on 2024-11-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_order_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='invoices',
            field=models.ManyToManyField(to='orders.invoice'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
